const userStories = [
    { story: "As a user, I want to log in with my email and password so that I can access my personal account.", category: "Authentication" },
    { story: "As a user, I want to log in using my social media account (e.g., Facebook, Google) to simplify the login process.", category: "Authentication" },
    { story: "As an admin, I need to log in with a higher level of security to access the admin panel and manage the application.", category: "Authentication" },
    { story: "As a returning user, I want the option to remain logged in to avoid entering my credentials each time I use the app.", category: "Authentication" },
    { story: "As a user, I want to reset my password if I forget it so that I can regain access to my account.", category: "Authentication" },
    { story: "As a user, I want to be prompted to create a strong password to secure my account.", category: "Authentication" },
    { story: "As a user, I want to change my password from my account settings for security reasons.", category: "Authentication" },
    { story: "As an admin, I need to enforce password complexity requirements to enhance account security.", category: "Authentication" },
    { story: "As a user, I want to set up multi-factor authentication to add an extra layer of security to my account.", category: "Authentication" },
    { story: "As a user, I need to receive a one-time code on my phone or email as part of multi-factor authentication.", category: "Authentication" },
    { story: "As an admin, I want to require multi-factor authentication for all users to ensure higher security standards.", category: "Authentication" },
    { story: "As a new user, I want to verify my email address or phone number to activate my account.", category: "Authentication" },
    { story: "As an admin, I need to ensure that all accounts are verified to maintain data integrity.", category: "Authentication" },
    { story: "As a user, I want to see where and when my account was last accessed for monitoring suspicious activities.", category: "Authentication" },
    { story: "As a user, I want to be able to log out from all devices for security purposes.", category: "Authentication" },
    { story: "As an admin, I need to be able to terminate any active user sessions if a security breach is suspected.", category: "Authentication" },
    { story: "As a user, I want to link or unlink my social media accounts with my app account for easier management.", category: "Authentication" },
    { story: "As a user, I wish to see which social media accounts are linked to my app account.", category: "Authentication" },
    { story: "As a user, I want to set up security questions to recover my account if I lose access.", category: "Authentication" },
    { story: "As an admin, I need the option to enable or disable specific authentication methods based on security protocols.", category: "Authentication" },
    { story: "As a user, I want to update my profile information (name, username) to keep my account current.", category: "Account Management" },
    { story: "As a user, I want to upload or change my profile photo to personalize my account.", category: "Account Management" },
    { story: "As a user, I want to specify a preferred name so I am not referred to by my legal name.", category: "Account Management" },
    { story: "As a user, I want to add or update my contact details (email, phone number, address) for accurate communication and account recovery purposes.", category: "Account Management" },
    { story: "As a user, I wish to verify or change my email address to ensure it's correct and secure.", category: "Account Management" },
    { story: "As a user, I need to add or edit my shipping and billing address for order processing.", category: "Account Management" },
    { story: "As a user, I want to adjust my account privacy settings to control who can see my profile and activity.", category: "Account Management" },
    { story: "As a user, I need to be able to set and change my communication preferences (like email or SMS notifications).", category: "Account Management" },
    { story: "As a user, I want to view my account activity or history to monitor my actions and interactions within the app.", category: "Account Management" },
    { story: "As a user, I want to be able to download my account data for personal backup and review.", category: "Account Management" },
    { story: "As a user, I want to deactivate my account temporarily, preserving my data for future use.", category: "Account Management" },
    { story: "As a user, I want to permanently delete my account and all its associated data for privacy reasons.", category: "Account Management" },
    { story: "As a user, I want to link or unlink other social media accounts to my main account for easier access and integration.", category: "Account Management" },
    { story: "As a user, I wish to set up or change language preferences to use the application in my preferred language.", category: "Account Management" },
    // ... Your user stories ...
];
export default userStories;
